### ISSUE TITLE
Allow reqwest to use rustls 

### ISSUE THREAD

**Issue by fdoyon** [sreeise/graph-rs#395]
The build fails when targeting environments that do not have openssl (AWS lambda) - fix should be as simple as adding the `default-features=false` to the `reqwest` dependencies.

**Comment by sreeise** [comment]
Hey @fdoyon ,

To be honest I am not as familiar with what setting `default-features=false` does but I will look into it. Feel free to let me know if you know more about it. I assume it has to do with switching what tls library is used? 

I am open to adding that to the dependencies for reqwest. I just want to make sure it doesnt cause any unintended side effects. I will get back to you soon on this hopefully. Sorry for the delay.

**Comment by sreeise** [comment]
Looking at it further I think it would be adding `default-features=false` and adding someting like `rustls-tls` since without default-features you cannot call https requests from what I can tell (only http).

**Comment by fdoyon** [comment]
Hi, thanks for looking into it.

When you drag reqwest, by default, it drags the `native-tls` crate which is calling `openssl-sys` on most platforms.

If you want to allow your clients to choose whether they want `native-tls` or `rustls` I think you might want to do the  following:

1. Define your dependencies on rustls with the minimum amount of features
2. create a `nativetls` feature on your crate, that then drags `reqwest.nativetls`
3. create a `rustls-ts` feature on your crate, that then drags `reqest.rustls-tls`
4. create a `default` feature that contains all the default features of your crate (and that may include `nativetls` so as not to break the current default behaviour
5. Users that want to use `rustls` would then import `graph-rs  = {version="0.3", default-features=false, features = ["rustls-tls"]

That's from looking at what crates like axum do when specifying their tls flavour, but I might be wrong.

``` toml

[dependencies]
reqwest = { version = "0.11", default-features = false, features = ["json", "gzip", "blocking", "stream"] }

[features]
default = ["nativetls"]
nativetls = ["reqwest/nativetls"] # define a nativetls feature of our crate that enables reqwest's nativetls feature
rustls-tls = ["reqwest/rustls-tls] # define a rustls feature of our crate that that enables reqwest's rustls-tls feature
```

This is from the cargo book : https://doc.rust-lang.org/cargo/reference/features.html

If the client crate already defines a dependency on `reqwest`, these will supercede any feature you may describe , as far as I can tell features are additive, but the consumer has priority when it comes to conflict resolution.
